### ISSUE TITLE
Don't watch the root folder with Chokidar in pleeease-watch

### ISSUE THREAD

**Issue by yaycmyk** [iamvdo/pleeease-cli#10]
You can see it at https://github.com/iamvdo/pleeease-cli/blob/master/lib/cli.js#L234

Instead, you should try to supply the contents of `"in"` in the `.pleeeaserc` to chokidar's watch (should accept the globbing pattern as-is) so it is doing the minimum necessary work and not consuming extra resources.

**Comment by yaycmyk** [comment]
There's something fishy going on - going to look into it further. I'm seeing non-css/scss stuff being picked up on change events for the whole directory tree.

```
Pleeease Recompiled file node_modules/pleeease-cli/bin/pleeease-watch
```

**Comment by iamvdo** [comment]
Thanks for the issue.

>you should try to supply the contents of "in" in the .pleeeaserc to chokidar's watch

Yes, already tested that but there's a problem with imported files. Much complicated than it looks.

>Pleeease Recompiled file node_modules/pleeease-cli/bin/pleeease-watch

This is weird. [Only CSS files should be watched](https://github.com/iamvdo/pleeease-cli/blob/master/lib/cli.js#L243).

**Comment by yaycmyk** [comment]
@iamvdo Yeah, I ended up making some modifications to a fork to make things behave. Would love to hear your thoughts: https://github.com/yaycmyk/pleeease-cli/commit/b45c6bb26f0d18171fd1a7e7e5acb3cd3a8a97cf

**Comment by yaycmyk** [comment]
Closing this, the open PR is sufficient
