### ISSUE TITLE
Watch command compile all files

### ISSUE THREAD

**Issue by iamvdo** [iamvdo/pleeease-cli#2]
Watch command should only watch input files.

**Comment by oilvier** [comment]
Ah, j'allais justement en parler !

**Comment by iamvdo** [comment]
This should be fixed in 3.2.5. Anyone confirm ?

**Comment by oilvier** [comment]
ça semble corrigé, mais ça amène un autre problème de mon côté.

J'ai un fichier `main.css` qui contient des `@import` de fichiers et qui doit être compilé vers `screen.css`
```
"in": [
	"build/main.css"
],
"out": "screen.css",
```
Depuis la MàJ en 3.2.5, si je fais une modification dans l'un des fichiers qui est importé dans `main.css`, le fichier n'est plus compilé vers `screen.css`. Seule la modification du fichier `main.css` recompile le tout.

**Comment by oilvier** [comment]
(Je précise que le problème que j'avais jusqu'ici, c'est qu'il watchait tous les fichiers du dossier, même les polices en .ttf ou .otf)

**Comment by iamvdo** [comment]
Fixed in 3.2.6
So now it watches all files, but ignore all non-CSS ones.

**Comment by oilvier** [comment]
C'est bon de mon côté.
Par contre, est-ce que c'est normal qu'il watch dans le dossier contenant le fichier `.pleeeaserc` plutôt que dans le dossier définit dans "in" ?

Voilà mon arbo : 
```
css/.pleeeaserc
css/screen.css (fichier de sortie)

css/build/main.css (fichier d'entrée)
css/build/*.css (fichiers appelés dans le fichier d'entrée)

css/ie.css
css/admin/*.css (fichiers qui n'ont pas besoin d'être watch)
```

**Comment by iamvdo** [comment]
Pour le moment, il watch le dossier courant de manière récursive. Mais oui, il faudrait peut-être limiter au(x) dossier(s) de départ.

**Comment by oilvier** [comment]
Je ne sais pas si c'est lié, mais apparement les fichiers avec un "." ne sont pas watch.
Par exemple :
`__bootstrap.layout.scss` n'est pas watch
`__bootstraplayout.scss` ou `__bootstrap-layout.scss` sont bien watch
