### ISSUE TITLE
Erreurs de compilation

### ISSUE THREAD

**Issue by oilvier** [iamvdo/pleeease-cli#3]
Depuis cette nouvelle version, je remarque des erreurs récurrentes lors de la compilation d'un fichier (avec `pleeeease watch`) sans que j'arrive à en identifier la cause.

En général, j'ai des erreurs lorsqu'il y a une coquille dans mon fichier (le ctrl+s compulsif peut amener à sauvegarder un fichier avec une règle CSS non fermée :)), mais là j'ai l'impression que ce n'est pas lié.

Voilà l'erreur que j'ai :

![erreur-pleeease](https://cloud.githubusercontent.com/assets/1795640/6503625/00a61872-c32f-11e4-9036-71e42d51c2de.png)

Une idée d'où ça peut venir ?

**Comment by iamvdo** [comment]
Ce qui est bizarre à première vue, c'est que les erreurs ne sont pas signalées aux bonnes lignes.
`lib/cli.js:127:29`: ligne vide par exemple. 
As tu la dernière version ? Sinon `npm update -g pleeease-cli`

**Comment by oilvier** [comment]
J'étais en 3.2.0.
Je viens de faire un update et maintenant j'ai une erreur dès que je fais appel à `pleeease`
![erreur-pleeease](https://cloud.githubusercontent.com/assets/1795640/6505494/0c65ca40-c343-11e4-9c4b-3d1f77ab8c54.png)

**Comment by oilvier** [comment]
Toujours le problème en 3.2.1, mais en effet les lignes ne sont plus les mêmes :
![erreur-pleeease](https://cloud.githubusercontent.com/assets/1795640/6506116/ac9e7fca-c348-11e4-97d8-b5e36a5358ac.png)

**Comment by oilvier** [comment]
Pas rencontré le problème sur les nouvelles versions.
