### ISSUE TITLE
Only works in current directory?

### ISSUE THREAD

**Issue by anselmh** [iamvdo/pleeease-cli#5]
Hey,

I just use the CLI in a new project here (btw it would be cool to offer all options via CLI options instead of rc-file as well) but I figured out that running `pleeease compile` does only work with files from the current directory here.

Doesn’t work:
`pleeease compile modules/main.css -t modules/main.min.css` -> `Pleeease File(s) not found`

Works:
`pleeease compile main.css -t main.min.css`

Is there any chance to fix this? I’m using the latest version of the package. Weirdly though, it seems to work using the `.pleeeaserc` file (which doesn’t work for me as I need to use a npm variable in the path for versioning).

**Comment by iamvdo** [comment]
Can't reproduce.
Can you share your complete structure ?

**Comment by anselmh** [comment]
Hey,

in package.json I have:
`"css": "mkdirp Public/asset && pleeease compile modules/main.css -t Public/asset/latest/default.css",`
and when running `npm run css` this returns with the error: `Pleeease File(s) not found`.
Of course the folder and files all exist and when running it inside modules folder it works seamlessly. Weirdly enough it works fine when using the rc file with the same path, too.

What else do you need for information?

**Comment by iamvdo** [comment]
This works for me. Weird it doesn't for you.
Try reinstall pleeease-cli ?

**Comment by anselmh** [comment]
Did that, doesn’t work. I don’t have a `"in" and `"out"` in the rc file and run the command above. Did you do that, too?

**Comment by iamvdo** [comment]
Yep.
I tested with simple structure and your npm script, without rc files. 
What is your platform ?

**Comment by anselmh** [comment]
OS X (10.10) and node@0.12.0.

tested without a rc file (which isn’t an option btw as I can’t set the other options via CLI arguments AFAIK) and it "works", except that it resolves the CSS imports completely wrong (it tries to resolve it from where the script is executed instead of where the source file is.

**Comment by iamvdo** [comment]
Tested on W7, with node@0.10.38 and node@0.12.0: works. Will test on OSX this evening (sorry).

Imports are resolved according to the output file, or cwd if not defined.

We should first find why you get the 'No file(s) found' error.

**Comment by anselmh** [comment]
So basically it I have no idea how I could track this down further.
It does not happen when no rc file is provided (then I’m running into the cwd issue) but only when I specify a path in the CLI and don’t in the rc file (rc seems to overwrite CLI arguments which is odd imo btw). Then I’m getting the "file not found" error. I thing it might be that default for rc file is *.css (there’s none in the same directory as the rc file is in) and CLI arguments are overwritten by rc file defaults.
Could that be the case?

**Comment by iamvdo** [comment]
Wait, it's a bit confusing now :)

What are you trying to do ?

- `pleeease compile in.css -t out.css` WITHOUT `.pleeeaserc` file ?
- `pleeease compile in.css -t out.css` WITH `.pleeeaserc` file with `in` and/or `out` ?
- other ?

**Comment by anselmh** [comment]
Hi,

- `pleeease compile in.css -t out.css` WITHOUT `.pleeeaserc` file
    - works fine
- `pleeease compile in.css -t out.css` WITH `.pleeeaserc` file with `in` and/or `out`
    - does use the `in` and `out` value of the `.pleeeaserc` file, not as intended, the compile CLI arguments

But I need something else which is theoretically achievable in two ways:
1. `pleeease compile in.css -t out.css` WITH `.pleeeaserc` file without `in` and `out`
    - as I’m specifying arguments this should work (but doesn’t)
2. `pleeease compile in.css -t out.css` WITHOUT `.pleeeaserc` file but options set via CLI arguments instead
    - doesn’t work as not all options are possible to set as arguments in the command line

**Why do I need to set in and out via CLI?**
Because I’m using a node variable in the path which is unresolvable if in a external file.

Still some questions or clearer now? :)

**Comment by iamvdo** [comment]
I think it's clearer now :) 
You need to use CLI in and out, and a `.pleeeaserc` file only for options, right ?

1. This should work and this works for me. Can you precise a bit ? Your issue is here...
2. Not supported at the moment, right

**Comment by anselmh** [comment]
Okay, then I’d love to get 2 as a feature-request.

Here’s a complete example of my version 1 code:

`.pleeeaserc`:

	{
		"rem": false,
		"autoprefixer": true,
		"filters": true,
		"pseudoElements": false,
		"opacity": false,
		"import": true,
		"minifier": true,
		"mqpacker": false,
		"sourcemaps": {
			"map": {
				"inline": false
			}
		},
		"next": {
			"calc": true,
			"customProperties": true
		}
	}

CLI executable:
`mkdirp Public/asset && pleeease compile modules/main.css -t Public/asset/latest/default.css`

**Comment by iamvdo** [comment]
Oh, I see, you're using sourcemaps. This is the bug.
It should be fixed now. Can you test ?

Btw, I'm currently rewriting clean CLI, to get options ;)

**Comment by anselmh** [comment]
Hey, sorry for the long delay. I was on holiday and tested it today. v3.2.5 seems to fix my issues and I can confirm it was somehow related to sourcemaps option (though it didn’t work properly by just removing sourcemap option from the rc file).

Anyway, it’s fixed in the new version so I say thank you! It’s also great to hear you’re rewriting the CLI to accept all options. :)
