### ISSUE TITLE
La minification n'élimine pas les commentaires avec des ##

### ISSUE THREAD

**Issue by oilvier** [iamvdo/pleeease-cli#7]
Si les sources comprennent des commentaires de type : 
``````
/* ## Commentaire
=====================*/
/* ### Commentaire
=====================*/
``````
Ces commentaires sont conservés dans le fichier en sortie

**Comment by iamvdo** [comment]
Je n'arrive pas a reproduire. Normalement, seuls les commentaires commençant par `/*!` sont conservés par défaut.

**Comment by oilvier** [comment]
On dirait que c'est corrigé sur la version 3.2.8. 
J'étais 3.2.6 jusqu'ici.

Désolé !

**Comment by iamvdo** [comment]
Pas de soucis. Tant mieux.
