### ISSUE TITLE
En mode Sass, les fichiers avec un @import n'apparaissent pas dans les source maps

### ISSUE THREAD

**Issue by oilvier** [iamvdo/pleeease-cli#8]
Lorsque l'option `"sass":true` est activée, les fichiers comportant un @import d'un autre fichier ne sont pas inclus dans les source maps.

Versions :
pleeease-cli 3.2.8
pleeeease 3.3.0

**Comment by oilvier** [comment]
Désolé de relancer, mais le problème est assez pénalisant.
Une idée pour corriger le problème ?

**Comment by iamvdo** [comment]
Je n'ai pas trop le temps là, mais peux tu déjà créer un test case ? Ça me permettra de tester plus rapidement dès que j'aurais un moment. :)

**Comment by oilvier** [comment]
Oui pas de soucis. Mais je présente ça comment ? 
Je t'envoie le fichier .map ? Tous les fichiers concernés ?

**Comment by oilvier** [comment]
Des nouvelles ?

**Comment by oilvier** [comment]
Je viens d'update vers la version 4.0.0 dans l'espoir que ça corrige ce problème mais malheureusement ce n'est pas le cas...

**Comment by oilvier** [comment]
Corrigé sur la version 4.0.2 de pleeease
